services:
  db:
    container_name: postgres_container
    image: postgres:14.17
    ports:
      - "5000:5432"
    environment:
      POSTGRES_DB: stock_db
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: db_password
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  #setup-bash:
    # build:
    #   context: .
    #   dockerfile: Dockerfile.bash
    # image: myrepo/setup:bash
  
  setup-powershell:
    build:
      context: .
      dockerfile: Dockerfile.powershell
    image: myrepo/setup:powershell